apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nzl9vxuwe-go 
  janus-idp.io/tekton: nzl9vxuwe-go
  backstage.io/kubernetes-id: nzl9vxuwe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nzl9vxuwe-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  