apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nzl9vxuwe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nzl9vxuwe-go 
  name: nzl9vxuwe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nzl9vxuwe-go 
